# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'trc-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for trc-ios

  target 'trc-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'trc-iosUITests' do
    # Pods for testing
  end

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'
  
  # Wrapper for Keychain access
  pod 'KeychainSwift', '~> 18.0'

end

# Prevent warning during build about deployment targets:
# https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end
